name: GitBook CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: 安装 GitBook CLI
        run: |
          npm install -g gitbook-cli
          gitbook install

      - name: 构建 GitBook
        run: |
          gitbook build

      # 如果你需要部署到 GitHub Pages，可以添加以下步骤
      - name: 部署到 GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_book