name: GitBook CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      reason:
        description: '触发构建的原因'
        required: false
        default: '手动触发构建'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: 安装 GitBook CLI
        run: |
          npm install -g gitbook-cli
          gitbook install

      - name: 构建 GitBook
        run: |
          gitbook build

      - name: 部署到 GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_book