name: GitBook CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      reason:
        description: '触发构建的原因'
        required: false
        default: '手动触发构建'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: 安装 HonKit
        run: |
          npm install -g honkit

      - name: 准备文档目录
        run: |
          if [ ! -f "./README.md" ]; then
            echo "# Documentation" > README.md
            echo "This is the documentation home page." >> README.md
          fi
          if [ ! -f "./SUMMARY.md" ]; then
            echo "# Summary" > SUMMARY.md
            echo "" >> SUMMARY.md
            echo "* [Introduction](README.md)" >> SUMMARY.md
          fi

      - name: 构建文档
        run: |
          honkit build . --log=error

      - name: 部署到 GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_book
